site_name: WriteUpHub
repo_url: https://github.com/MattSilverio/WriteUpHub
repo_name: MattSilverio/WriteUpHub

theme:
  name: material
  language: pt
  logo: ./images/hacker.png
  favicon: ./images/hacker.png
  features:
    - navigation.footer
    - header.autohide

  plugins:
    - mkdocs-video
  
  favicon: ./images/hacker.png
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Início: index.md
  

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html